#!/bin/bash

# Exit on error
set -e

# Script for pushing a built web app to my website repo
if [ "${PWD##*/}" != 'portfolio_web' ]; then
    echo 'Called from wrong directory!'
    echo 'run from the project root directory!'
    exit 0
fi

START="${PWD}"
GIT_PATH='./build/web'
TARGET_REPO='git@github.com:mah-dvlpr/mah-dvlpr.github.io.git'
SRC_REPO="# About:\nThis repo/commit is a snapshot of branch '$(git branch --show-current)' (commit: $(git rev-parse HEAD)) generated via the repo at $(git config --get remote.origin.url | tr ':' '/' | sed -e 's#git@#https://#' -e 's/.git$//')."

# Build project
flutter build web

# Push
cd "${GIT_PATH}"
rm -rf .git
git init
echo -e "${SRC_REPO}" > README.md
git checkout -b main
git add -A
git commit -am 'Web build push'
git push -f --mirror "${TARGET_REPO}"
cd "${PWD}"